all: img/tls1.2.svg img/tls1.3.svg img/1-rtt.svg img/0-rtt.svg

.txt.svg:
	uml2img $?

img/tls1.2.svg: img/tls1.2.txt
img/tls1.3.svg: img/tls1.3.txt
img/1-rtt.svg: img/1-rtt.txt
img/0-rtt.svg: img/0-rtt.txt
