// @ts-nocheck
import createModule from './bbs_c.js'
import getRandomValues from './getRandomValues'

// ciphersuite
export const BLS12381_SHA256 = 0

// size of the structures in the wasm memory
const BBS_SECRETKEY_SIZE = 32
const BBS_PUBLICKEY_SIZE = 48*2*3
const BBS_SIGNATURE_SIZE = 48*3+32

/** @internal singleton of bbs WASM module generated by emscripten. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export let mod: Record<string, any>

export const ptrToAsciiStr = (pos: number, n: number): string => {
  let s = ''
  for (let i = 0; i < n; i++) {
    s += String.fromCharCode(mod.HEAP8[pos + i])
  }
  return s
}

export const asciiStrToPtr = (pos: number, s: string): void => {
  for (let i = 0; i < s.length; i++) {
    mod.HEAP8[pos + i] = s.charCodeAt(i)
  }
}

export const toHex = (a: Uint8Array, start: number, n: number): string => {
  let s = ''
  for (let i = 0; i < n; i++) {
    s += ('0' + a[start + i].toString(16)).slice(-2)
  }
  return s
}

// Uint8Array to hex string
export const toHexStr = (a: Uint8Array): string => {
  return toHex(a, 0, a.length)
}

// hex string to Uint8Array
export const fromHexStr = (s: string): Uint8Array => {
  if ((s.length & 1) !== 0) throw new Error(`fromHexStr:length must be even (${s.length})`)
  const n = s.length / 2
  const a = new Uint8Array(n)
  for (let i = 0; i < n; i++) {
    a[i] = parseInt(s.slice(i * 2, i * 2 + 2), 16)
  }
  return a
}

export const free = (x: number): void => {
  mod._free(x)
}

type ToStrFunc = (x: number) => Uint8Array

const addWrappedMethods = (): void => {
  type StringReader = (pos: number, maxBufSize: number, x: number) => number
  const _wrapSerialize = (func: StringReader): ToStrFunc => {
    return (x: number) => {
      const stack = mod.stackSave()
      const maxBufSize = 8192
      const pos: number = mod.stackAlloc(maxBufSize)
      const n = func(pos, maxBufSize, x)
      if (n > 0) {
        let s = new Uint8Array(mod.HEAP8.subarray(pos, pos + n))
        mod.stackRestore(stack)
        return s
      } else {
        mod.stackRestore(stack)
        throw new Error(`err gen_str:${x}`)
      }
    }
  }

  type StringWriter = (pos: number, maxBufSize: number, x: number) => number
  const _wrapDeserialize = (func: StringWriter) => {
    return (x: number, buf: Uint8Array) => {
      const stack = mod.stackSave()
      const pos = mod.stackAlloc(buf.length)
      mod.HEAP8.set(buf, pos)
      const r = func(x, pos, buf.length)
      mod.stackRestore(stack)
      if (r === 0 || r !== buf.length) throw new Error(`err _wrapDeserialize: ${r} != ${buf.length}`)
    }
  }

  mod.g_his = []
  mod.g_ptr = {}
  mod.g_total = 0
  /*
    she libray always uses (malloc,free) in nested pairs.
  */
  mod._mallocDebug = (size: number): number => {
    const p = mod._mallocOrg(size + 4)
    mod.HEAP8[p + size] = 0x12
    mod.HEAP8[p + size + 1] = 0x34
    mod.HEAP8[p + size + 2] = 0x56
    mod.HEAP8[p + size + 3] = 0x78
    mod.g_his.push([p, size])
    mod.g_ptr[p] = size
    mod.g_total += size
    return p
  }
  mod._freeDebug = (pos: number): void => {
    const ps = mod.g_his.pop()
    const p = ps[0]
    const size = ps[1]
    if (pos !== p) {
      console.log(`pos=${pos} oldPos=${p}`)
    }
    const v = mod.HEAP8[p + size] + (mod.HEAP8[p + size + 1] << 8) + (mod.HEAP8[p + size + 2] << 16) + (mod.HEAP8[p + size + 3] << 24)
    if (v !== 0x78563412) {
      console.log(`ERR=${p} v=${v.toString(16)}`)
    }
    mod._freeOrg(pos)
    const s = mod.g_ptr[pos]
    if (s === 0) {
      console.log(`ERR ${pos}`)
    } else {
      delete mod.g_ptr[pos]
      mod.g_total -= s
    }
  }
  mod._mallocOrg = mod._malloc
  mod._freeOrg = mod._free
  mod.debug = false
  if (mod.debug) {
    mod._malloc = mod._mallocDebug
    mod._free = mod._freeDebug
  }
  mod.bbsDeserializeSecretKey = _wrapDeserialize(mod._bbsDeserializeSecretKey)
  mod.bbsSerializeSecretKey = _wrapSerialize(mod._bbsSerializeSecretKey)
  mod.bbsDeserializePublicKey = _wrapDeserialize(mod._bbsDeserializePublicKey)
  mod.bbsSerializePublicKey = _wrapSerialize(mod._bbsSerializePublicKey)
  mod.bbsDeserializeSignature = _wrapDeserialize(mod._bbsDeserializeSignature)
  mod.bbsSerializeSignature = _wrapSerialize(mod._bbsSerializeSignature)
}

export const _showDebug = () => {
  if (mod.debug) {
    console.log('malloc DEBUG mode')
    console.log(`  show total=${mod.g_total}`)
    console.log(`  g_ptr=${JSON.stringify(mod.g_ptr, null, '\t')}`)
  }
}

/*
  initialize the library
  maxMsgN: max number of messages
*/
export const init = async (maxMsgN = 128): Promise<void> => {
  mod = await createModule({
    // fill a with random values. the glue copies it into the wasm memory
    cryptoGetRandomValues: (a: Uint8Array) => {
      getRandomValues(a)
    },
    // export bbs* functions as mod._bbs*
    prefix: 'bbs'
  })

  addWrappedMethods()

  if (BBS_SECRETKEY_SIZE !== mod._bbsSizeofSecretKey()) throw new Error(`BBS_SECRETKEY_SIZE=${BBS_SECRETKEY_SIZE} !== mod._bbsSizeofSecretkey()=${mod._bbsSizeofSecretkey()}`)
  if (BBS_PUBLICKEY_SIZE !== mod._bbsSizeofPublicKey()) throw new Error(`BBS_PUBLICKEY_SIZE=${BBS_PUBLICKEY_SIZE} !== mod._bbsSizeofPublicKey()=${mod._bbsSizeofPublicKey()}`)
  if (BBS_SIGNATURE_SIZE !== mod._bbsSizeofSignature()) throw new Error(`BBS_SIGNATURE_SIZE=${BBS_SIGNATURE_SIZE} !== mod._bbsSizeofSignature()=${mod._bbsSizeofSignature()}`)

  const r: boolean = mod._bbsInit(BLS12381_SHA256, maxMsgN)
  if (!r) throw new Error('_bbsInit err')
}

// free the memory allocated by init
export const term = (): void => {
  mod._bbsTerm()
}

abstract class Common {
  /** @internal */
  public a_: Uint32Array

  constructor (size: number) {
    this.a_ = new Uint32Array(size / 4)
  }

  deserializeHexStr (s: string): void {
    this.deserialize(fromHexStr(s))
  }

  serializeToHexStr (): string {
    return toHexStr(this.serialize())
  }

  dump (msg = ''): void {
    console.log(msg + this.serializeToHexStr())
  }

  clear (): void {
    this.a_.fill(0)
  }

  // copy to allocated memory
  copyToMem (pos: number): void {
    mod.HEAP32.set(this.a_, pos / 4)
  }

  // copy from allocated memory
  copyFromMem (pos: number): void {
    this.a_.set(mod.HEAP32.subarray(pos / 4, pos / 4 + this.a_.length))
  }

  abstract isEqual (rhs: this): boolean
  abstract deserialize (v: Uint8Array): void
  abstract serialize (): Uint8Array

  // internal methods

  /** @internal alloc new array */
  _alloc (): number {
    return mod._malloc(this.a_.length * 4)
  }

  /** @internal stack alloc new array */
  _salloc (): number {
    return mod.stackAlloc(this.a_.length * 4)
  }

  /** @internal alloc and copy a_ to mod.HEAP32[pos / 4] */
  _allocAndCopy (): number {
    const pos = this._alloc()
    mod.HEAP32.set(this.a_, pos / 4)
    return pos
  }

  /** @internal stack alloc and copy a_ to mod.HEAP32[pos / 4] */
  _sallocAndCopy (): number {
    const pos = this._salloc()
    mod.HEAP32.set(this.a_, pos / 4)
    return pos
  }

  /** @internal save pos to a_ */
  _save (pos: number): void {
    this.a_.set(mod.HEAP32.subarray(pos / 4, pos / 4 + this.a_.length))
  }

  /** @internal save and free */
  _saveAndFree (pos: number): void {
    this._save(pos)
    mod._free(pos)
  }

  /** @internal */
  _isEqual (func: (xPos: number, yPos: number) => number, rhs: Common): boolean {
    const stack = mod.stackSave()
    const xPos = this._sallocAndCopy()
    const yPos = rhs._sallocAndCopy()
    const r = func(xPos, yPos)
    mod.stackRestore(stack)
    return r === 1
  }
  /** @internal set parameter */
  _setter (func: Function, ...params: unknown[]): void {
    const stack = mod.stackSave()
    const pos = this._salloc()
    const r = func(pos, ...params)
    this._save(pos)
    mod.stackRestore(stack)
    if (r !== undefined && r !== 0) throw new Error('_setter err')
  }

  /** @internal getter */
  _getter (func: Function, ...params: unknown[]): unknown {
    const stack = mod.stackSave()
    const pos = this._sallocAndCopy()
    const s = func(pos, ...params)
    mod.stackRestore(stack)
    return s
  }

  /** @internal devide Uint32Array a into n and chose the idx-th */
  _getSubArray (idx: number, n: number): Uint32Array {
    const d = this.a_.length / n
    // return new Uint32Array(this.a_.buffer, d * idx * 4, d) // err : return reference to the buffer
    // correct : make new buffer and copy it
    return new Uint32Array(new Uint32Array(this.a_.buffer, d * idx * 4, d))
  }

  /** @internal set array lhs to idx */
  _setSubArray (lhs: Common, idx: number, n: number): void {
    const d = this.a_.length / n
    this.a_.set(lhs.a_, d * idx)
  }
}

interface HasArray {
  a_: Uint32Array;
}

const _cloneArray = <T extends HasArray> (x: T): T=> {
  const cstr = x.constructor as new () => T
  const r = new cstr()
  r.a_.set(x.a_)
  return r
}

export class SecretKey extends Common {
  constructor () {
    super(BBS_SECRETKEY_SIZE)
  }

  deserialize (s: Uint8Array): void {
    this._setter(mod.bbsDeserializeSecretKey, s)
  }

  serialize (): Uint8Array {
    return this._getter(mod.bbsSerializeSecretKey)
  }
  isEqual (rhs: this): boolean {
    return this._isEqual(mod._bbsIsEqualSecretKey, rhs)
  }

  clone (): SecretKey { return _cloneArray<SecretKey>(this) }

  // initialize secret key with random values
  init (): void {
    const stack = mod.stackSave()
    const pos = this._salloc()
    const r = mod._bbsInitSecretKey(pos)
    this._save(pos)
    mod.stackRestore(stack)
    if (!r) throw new Error('SecretKey::init error')
  }

  /*
    KeyGen of the spec
    keyMaterial: secret octet string (at least 32 bytes)
    keyInfo: optional
    keyDst: optional. the default dst is used if it is not specified
  */
  keyGen (keyMaterial: Uint8Array, keyInfo?: Uint8Array, keyDst?: Uint8Array): void {
    const stack = mod.stackSave()
    const pos = this._salloc()
    const [keyMaterialPos, keyMaterialSize] = sallocBytes(keyMaterial)
    const [keyInfoPos, keyInfoSize] = sallocBytes(keyInfo)
    const [keyDstPos, keyDstSize] = sallocBytes(keyDst)
    const r = mod._bbsKeyGen(pos, keyMaterialPos, keyMaterialSize, keyInfoPos, keyInfoSize, keyDstPos, keyDstSize)
    this._save(pos)
    mod.stackRestore(stack)
    if (!r) throw new Error('SecretKey::keyGen error')
  }

  // get public key from secret key
  getPublicKey (): PublicKey {
    const pub = new PublicKey()
    const stack = mod.stackSave()
    const secPos = this._sallocAndCopy()
    const pubPos = pub._salloc()
    const r = mod._bbsGetPublicKey(pubPos, secPos)
    pub._save(pubPos)
    mod.stackRestore(stack)
    if (!r) throw new Error('SecretKey::getPublicKey error')
    return pub
  }
}

export const deserializeHexStrToSecretKey = (s: string): SecretKey => {
  const r = new SecretKey()
  r.deserializeHexStr(s)
  return r
}

export class PublicKey extends Common {
  constructor () {
    super(BBS_PUBLICKEY_SIZE)
  }

  deserialize (s: Uint8Array): void {
    this._setter(mod.bbsDeserializePublicKey, s)
  }

  serialize (): Uint8Array {
    return this._getter(mod.bbsSerializePublicKey)
  }
  isEqual (rhs: this): boolean {
    return this._isEqual(mod._bbsIsEqualPublicKey, rhs)
  }

  clone (): PublicKey { return _cloneArray<PublicKey>(this) }
}

export const deserializeHexStrToPublicKey = (s: string): PublicKey => {
  const r = new PublicKey()
  r.deserializeHexStr(s)
  return r
}

export class Signature extends Common {
  constructor () {
    super(BBS_SIGNATURE_SIZE)
  }

  deserialize (s: Uint8Array): void {
    this._setter(mod.bbsDeserializeSignature, s)
  }

  serialize (): Uint8Array {
    return this._getter(mod.bbsSerializeSignature)
  }
  isEqual (rhs: this): boolean {
    return this._isEqual(mod._bbsIsEqualSignature, rhs)
  }

  clone (): Signature { return _cloneArray<Signature>(this) }
}

export const deserializeHexStrToSignature = (s: string): Signature => {
  const r = new Signature()
  r.deserializeHexStr(s)
  return r
}

/*
  message
  Uint8Array : octet string. it is hashed to a scalar (the same as the spec)
  bigint : integer in [0, 2^64). it is used as a scalar without hashing (not defined in the spec)
           a predicate of proofGenEx requires an integer message
*/
export type Msg = Uint8Array | bigint

// size of mclBnFr in the wasm memory
const BBS_FR_SIZE = 32
// size of bbsPredicate in the wasm memory
const BBS_PREDICATE_SIZE = 24

// copy a to the stack and return [pos, size]. [0, 0] if a is not specified
const sallocBytes = (a?: Uint8Array): [number, number] => {
  if (a === null || a === undefined || a.length === 0) return [0, 0]
  const pos = mod.stackAlloc(a.length)
  mod.HEAP8.set(a, pos)
  return [pos, a.length]
}

// make the scalars of msgs on the stack and return the position
const sallocMsgs = (msgs: Msg[]): number => {
  const pos = mod.stackAlloc(msgs.length * BBS_FR_SIZE)
  for (let i = 0; i < msgs.length; i++) {
    const m = msgs[i]
    const p = pos + i * BBS_FR_SIZE
    if (typeof m === 'bigint') {
      if (m < 0n || m >= (1n << 64n)) throw new Error(`bad integer message ${m}`)
      mod._bbsUint64ToFr(p, m)
    } else {
      const stack = mod.stackSave()
      const [msgPos, msgSize] = sallocBytes(m)
      mod._bbsMsgToFr(p, msgPos, msgSize)
      mod.stackRestore(stack)
    }
  }
  return pos
}

// copy idxs to the stack and return the position
const sallocIdxs = (idxs: Uint32Array): number => {
  const pos = mod.stackAlloc(idxs.length * 4)
  mod.HEAP32.set(idxs, pos / 4)
  return pos
}

/*
  sign msgs with secret key and public key
  header: optional
*/
export const sign = (sec: SecretKey, pub: PublicKey, msgs: Msg[], header?: Uint8Array): Signature => {
  const sig = new Signature()
  const stack = mod.stackSave()
  const sigPos = sig._salloc()
  const secPos = sec._sallocAndCopy()
  const pubPos = pub._sallocAndCopy()
  const [headerPos, headerSize] = sallocBytes(header)
  const msgsPos = sallocMsgs(msgs)

  const r = mod._bbsSignFr(sigPos, secPos, pubPos, headerPos, headerSize, msgsPos, msgs.length)
  sig._save(sigPos)
  mod.stackRestore(stack)
  if (!r) throw new Error('SecretKey::sign error')
  return sig
}

/*
  verify signature of msgs with public key
  header: header used in sign
*/
export const verify = (sig: Signature, pub: PublicKey, msgs: Msg[], header?: Uint8Array): boolean => {
  const stack = mod.stackSave()
  const sigPos = sig._sallocAndCopy()
  const pubPos = pub._sallocAndCopy()
  const [headerPos, headerSize] = sallocBytes(header)
  const msgsPos = sallocMsgs(msgs)

  const r = mod._bbsVerifyFr(sigPos, pubPos, headerPos, headerSize, msgsPos, msgs.length)
  mod.stackRestore(stack)
  return r === 1
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const dump = (pos: number, n: number, msg = '') => {
  const a = mod.HEAP8.subarray(pos, pos + n)
  console.log(`${msg} ${n} ${toHexStr(a)}`)
}

// size of a proof for undiscN undisclosed messages
export const getProofSize = (undiscN: number): number => {
  return mod._bbsGetProofSize(undiscN)
}

/*
  generate proof
  pub: public key
  sig: signature created for msgs
  msgs: messages
  discIdxs: indices of messages to be disclosed (strictly ascending order)
  header: header used in sign
  ph: optional presentation header
  return: proof
*/
export const proofGen = (pub: PublicKey, sig: Signature, msgs: Msg[], discIdxs: Uint32Array, header?: Uint8Array, ph?: Uint8Array): Uint8Array => {
  const msgN = msgs.length
  const discN = discIdxs.length
  if (discN > msgN) throw new Error(`proofGen:bad size. discIdxs.length=${discN} > msgs.length=${msgN}`)
  const proofSize = getProofSize(msgN - discN)
  const stack = mod.stackSave()
  const proofPos = mod.stackAlloc(proofSize)
  const pubPos = pub._sallocAndCopy()
  const sigPos = sig._sallocAndCopy()
  const [headerPos, headerSize] = sallocBytes(header)
  const [phPos, phSize] = sallocBytes(ph)
  const msgsPos = sallocMsgs(msgs)
  const discIdxsPos = sallocIdxs(discIdxs)
  const n = mod._bbsProofGenFr(proofPos, proofSize, pubPos, sigPos, headerPos, headerSize, phPos, phSize, msgsPos, msgN, discIdxsPos, discN)
  const proof = new Uint8Array(mod.HEAP8.subarray(proofPos, proofPos + n))
  mod.stackRestore(stack)
  if (n === 0) throw new Error('proofGen error')
  return proof
}

/*
  verify proof
  pub: public key
  proof: proof
  discMsgs: messages to be disclosed (discMsgs[i] = msgs[discIdxs[i]])
  discIdxs: indices of messages to be disclosed (strictly ascending order)
  header: header used in sign
  ph: presentation header used in proofGen
  return: true if proof is valid, false otherwise
*/
export const proofVerify = (pub: PublicKey, proof: Uint8Array, discMsgs: Msg[], discIdxs: Uint32Array, header?: Uint8Array, ph?: Uint8Array): boolean => {
  const discN = discMsgs.length
  if (discN !== discIdxs.length) throw new Error(`proofVerify:bad size. discMsgs.length=${discN} !== discIdxs.length=${discIdxs.length}`)

  const stack = mod.stackSave()
  const pubPos = pub._sallocAndCopy()
  const [proofPos, proofSize] = sallocBytes(proof)
  const [headerPos, headerSize] = sallocBytes(header)
  const [phPos, phSize] = sallocBytes(ph)
  const discMsgsPos = sallocMsgs(discMsgs)
  const discIdxsPos = sallocIdxs(discIdxs)
  const r = mod._bbsProofVerifyFr(pubPos, proofPos, proofSize, headerPos, headerSize, phPos, phSize, discMsgsPos, discIdxsPos, discN)
  mod.stackRestore(stack)
  return r === 1
}

/*
  extension which is not defined in the spec
  predicate for an undisclosed integer message m = msgs[idx]
  PRED_GE : 0 <= m - bound < 2^bitN
  PRED_LE : 0 <= bound - m < 2^bitN
  1 <= bitN <= 64
*/
export const PRED_GE = 0
export const PRED_LE = 1

export interface Predicate {
  idx: number
  type: number
  bound: bigint
  bitN: number
}

// copy preds to the stack as an array of bbsPredicate and return the position
const sallocPreds = (preds: Predicate[]): number => {
  const pos = mod.stackAlloc(preds.length * BBS_PREDICATE_SIZE)
  for (let i = 0; i < preds.length; i++) {
    const p = preds[i]
    if (p.bound < 0n || p.bound >= (1n << 64n)) throw new Error(`bad bound ${p.bound}`)
    // struct { uint64_t bound; uint32_t idx, type, bitN, reserved; }
    const q = (pos + i * BBS_PREDICATE_SIZE) >> 2
    const H = mod.HEAP32
    H[q] = Number(p.bound & 0xffffffffn)
    H[q + 1] = Number(p.bound >> 32n)
    H[q + 2] = p.idx
    H[q + 3] = p.type
    H[q + 4] = p.bitN
    H[q + 5] = 0
  }
  return pos
}

// size of a proof of proofGenEx. 0 if preds is invalid
export const getProofExSize = (undiscN: number, preds: Predicate[]): number => {
  const stack = mod.stackSave()
  const predsPos = sallocPreds(preds)
  const n = mod._bbsGetProofExSize(undiscN, predsPos, preds.length)
  mod.stackRestore(stack)
  return n
}

/*
  generate proof with predicates
  preds: predicates sorted by idx. idx must be an index of an undisclosed message
  the other parameters are the same as proofGen
  an exception is thrown if a predicate does not hold
*/
export const proofGenEx = (pub: PublicKey, sig: Signature, msgs: Msg[], discIdxs: Uint32Array, preds: Predicate[], header?: Uint8Array, ph?: Uint8Array): Uint8Array => {
  const msgN = msgs.length
  const discN = discIdxs.length
  if (discN > msgN) throw new Error(`proofGenEx:bad size. discIdxs.length=${discN} > msgs.length=${msgN}`)
  const proofSize = getProofExSize(msgN - discN, preds)
  if (proofSize === 0) throw new Error('proofGenEx:bad predicates')
  const stack = mod.stackSave()
  const proofPos = mod.stackAlloc(proofSize)
  const pubPos = pub._sallocAndCopy()
  const sigPos = sig._sallocAndCopy()
  const [headerPos, headerSize] = sallocBytes(header)
  const [phPos, phSize] = sallocBytes(ph)
  const msgsPos = sallocMsgs(msgs)
  const discIdxsPos = sallocIdxs(discIdxs)
  const predsPos = sallocPreds(preds)
  const n = mod._bbsProofGenEx(proofPos, proofSize, pubPos, sigPos, headerPos, headerSize, phPos, phSize, msgsPos, msgN, discIdxsPos, discN, predsPos, preds.length)
  const proof = new Uint8Array(mod.HEAP8.subarray(proofPos, proofPos + n))
  mod.stackRestore(stack)
  if (n === 0) throw new Error('proofGenEx error')
  return proof
}

/*
  verify proof with predicates
  preds: the same predicates as those of proofGenEx
  the other parameters are the same as proofVerify
*/
export const proofVerifyEx = (pub: PublicKey, proof: Uint8Array, discMsgs: Msg[], discIdxs: Uint32Array, preds: Predicate[], header?: Uint8Array, ph?: Uint8Array): boolean => {
  const discN = discMsgs.length
  if (discN !== discIdxs.length) throw new Error(`proofVerifyEx:bad size. discMsgs.length=${discN} !== discIdxs.length=${discIdxs.length}`)

  const stack = mod.stackSave()
  const pubPos = pub._sallocAndCopy()
  const [proofPos, proofSize] = sallocBytes(proof)
  const [headerPos, headerSize] = sallocBytes(header)
  const [phPos, phSize] = sallocBytes(ph)
  const discMsgsPos = sallocMsgs(discMsgs)
  const discIdxsPos = sallocIdxs(discIdxs)
  const predsPos = sallocPreds(preds)
  const r = mod._bbsProofVerifyEx(pubPos, proofPos, proofSize, headerPos, headerSize, phPos, phSize, discMsgsPos, discIdxsPos, discN, predsPos, preds.length)
  mod.stackRestore(stack)
  return r === 1
}
